[versions]
netty = "4.2.11.Final"
lombok = "1.18.44"
shadow = "9.3.2"
gson = "2.13.2"
configurate = "4.2.0"
kyori-adventure = "4.26.1"
lamp = "3.0.8"
velocity-api = "3.5.0-SNAPSHOT"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }

netty-handler = { module = "io.netty:netty-handler", version.ref = "netty" }
netty-transport-native-epoll = { module = "io.netty:netty-transport-native-epoll", version.ref = "netty" }
netty-transport-native-io_uring = { module = "io.netty:netty-transport-native-io_uring", version.ref = "netty" }
netty-transport-native-kqueue = { module = "io.netty:netty-transport-native-kqueue", version.ref = "netty" }

kyori-adventure-api = { module = "net.kyori:adventure-api", version.ref = "kyori-adventure" }
kyori-adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "kyori-adventure" }
kyori-adventure-text-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "kyori-adventure" }
kyori-adventure-text-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "kyori-adventure" }
kyori-adventure-text-serializer-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "kyori-adventure" }
kyori-adventure-text-serializer-json-legacy-impl = { module = "net.kyori:adventure-text-serializer-json-legacy-impl", version.ref = "kyori-adventure" }
kyori-adventure-nbt = { module = "net.kyori:adventure-nbt", version.ref = "kyori-adventure" }

lamp-common = { module = "com.github.Revxrsal.Lamp:common", version.ref = "lamp" }
lamp-velocity = { module = "com.github.Revxrsal.Lamp:velocity", version.ref = "lamp" }

velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api" }